spring:
    application:
        name: shop-oauth

    datasource:
        url: jdbc:mysql://localhost:3306/cloudauth
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    redis:
        host: localhost
        port: 6379
        pool:
            max-active: 20

server:
    port: 8301


logging:
    level:
        org:
            springframework:
                security: DEBUG

##很重要
security:
    oauth2:
        resource:
            filter-order: 3